import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const argon = localFont({
    src: "./fonts/Argon.ttf",
    variable: "--font-argon",
})

const neon = localFont({
    src: "./fonts/Neon.ttf",
    variable: "--font-neon",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${neon.className} ${argon.className} bg-gh-bg text-white`}
            >
                {children}
            </body>
        </html>
    )
}
